<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="MAIN" Id="{7d47c4d8-afbc-4278-8b7f-8e4ca1a04aee}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[GVL_PcDemo.MainCycleCounter := GVL_PcDemo.MainCycleCounter + 1;
GVL_PcDemo.EL3742_Ch2_Sample0_RawCopy := GVL_PcDemo.EL3742_Ch2_Sample0_Raw;
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="2" />
    </LineIds>
  </POU>
</TcPlcObject>
